version: '3.9'

services:
  user-db:
    image: postgres:14
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: userpassword
    volumes:
      - ./database/init-scripts/user-service:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - backend

  task-db:
    image: postgres:14
    environment:
      POSTGRES_DB: task_service_db
      POSTGRES_USER: mainuser
      POSTGRES_PASSWORD: userpassword
    volumes:
      - ./database/init-scripts/task-service:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
    env_file:
      - ./user-service/.env
    depends_on:
      - user-db
    ports:
      - "8001:8000"
    networks:
      - backend

  task-service:
    build:
      context: ./task-service
    env_file:
      - ./task-service/.env
    depends_on:
      - task-db
    ports:
      - "8002:8000"
    networks:
      - backend

  gateway-service:
    build:
      context: ./gateway-service
    env_file:
      - ./gateway-service/.env
    depends_on:
      - user-service
      - task-service
    ports:
      - "8003:8000"
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - gateway-service
    networks:
      - backend

networks:
  backend:
